services:
  postgres:
    container_name: floyd_postgres
    image: postgres:16.11-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: floyd_development
      POSTGRES_HOST_AUTH_METHOD: trust
    logging:
      driver: none

volumes:
  postgres_data:
    driver: local
