services:
  postgres:
    container_name: floyd_postgres
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: floyd_development
      POSTGRES_HOST_AUTH_METHOD: trust
    logging:
      driver: none
  postgres_test:
    container_name: floyd_postgres_test
    image: postgres:16.2
    volumes:
      - postgres_data_test:/var/lib/postgresql/data:delegated
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: floyd_test
      POSTGRES_HOST_AUTH_METHOD: trust
    logging:
      driver: none

volumes:
  postgres_data:
    driver: local
  postgres_data_test:
    driver: local
